# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

env:
  NAME: async-api-generator
  GIT_TAG: "0.0.0"
  VERSION: "v{{.GIT_TAG}}"
  REVISION: "aaaabbbb"
  NETCORE_TARGET_ARCH: "osx-arm64"
  GO_TARGET_ARCH: "darwin"

includes:
  schema-generator: src/dotnet/Schema.Generator/taskfile.yml
  async-api-generator: src/go/taskfile.yml
  eventcatalog-plugin: src/ts/taskfile.yml

tasks:
  node_prereq:
    internal: true
    cmds:
      - npm i -g pnpm@8.6.0
      - rm -rf dist node_modules .coverage

  install_node:
    desc: Install dependencies
    internal: true
    deps:
      - node_prereq
    cmds:
      - pnpm i

  install_workspace:
    desc: Install workspace dependencies
    internal: false
    deps:
      - node_prereq
    cmds:
      - cd src/go/async-api-gen-doc && go mod tidy
      - go work sync
      - pnpm i
  