# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  node_prereq:
    internal: true
    cmds:
      - npm i -g pnpm@8.6.0
      - rm -rf dist node_modules .coverage

  install:
    desc: Install dependencies
    internal: true
    dir: src/ts/eventcatalog-plugin-doc-generator-azblob
    deps:
      - node_prereq
    cmds:
      - pnpm i

  # EventCatalog Plugin tasks
  test:
    desc: Builds and tests the EventCatalog plugin
    dir: src/ts/eventcatalog-plugin-doc-generator-azblob
    summary: |
      Testing of the plugin and any local dependencies against a licence checker 
    deps:
      - install
    cmds: 
      - pnpm run license:check 
      - pnpm run test

  build:
    desc: Builds  the EventCatalog plugin
    dir: src/ts/eventcatalog-plugin-doc-generator-azblob
    summary: |
      Building and testing of the plugin and any local dependencies
    deps:
      - test
    cmds: 
      - pnpm run build 

  show_coverage: 
    desc: Opens the current coverage viewer for the the event catalog plugin.
    dir: src/ts/eventcatalog-plugin-doc-generator-azblob
    deps:
      - test
    cmd: pnpm run --filter @dnitsch/plugin-doc-generator-asyncapi-remote-source view:coverage

  publish:
    dir: src/ts/eventcatalog-plugin-doc-generator-azblob
    desc: Publishes to local NPM
    cmds: 
      - pnpm run build 
      - pnpm publish --no-git-checks --filter "@dnitsch/*"
  
